In [ ]:
import numpy as np
numbers = np.array([1,2,3])
type(numbers)
numbers
n1 = np.array([[1, 2, 3], [4, 5, 6]])
n1
np.array([x for x in range(2, 22, 2)])
integers = np.array([[1, 2, 3], [4, 5, 6]])
integers
floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])
floats
integers.dtype
floats.dtype
integers.ndim
floats.ndim
print(integers)
integers.shape
floats.shape
integers.size
integers.itemsize
# floats.size
# floats.itemsize


# np.zeros(5, dtype = int)
# np.ones((2, 4), dtype=float)
# np.full((3, 5), 13)
# np.arange(5)
# np.arange(5, 10)
# np.arange(10, 1, -2)
np.linspace(0.0, 1.0, num=5)
np.logspace(1.0, 2.0, num=10)
# numbers = np.array([0.0, 0.1, 0.2, 0.3, 0.4, 0.5])

[[1 2 3]
 [4 5 6]]


array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

In [ ]:
for row in integers:
  for column in row:
    print(column, end=' ')
  print()

1 2 3 
4 5 6 


In [ ]:
for i in integers.flat:
  print(i, end=' ')

1 2 3 4 5 6 

In [ ]:
# numbers = integers
numbers * 2
# numbers ** 3
# numbers
numbers += 10
# numbers
# numbers * [[2, 3, 2],[ 2, 2, 2]]
# numbers
# np.sqrt(numbers)
# np.add(numbers, numbers2)
print(numbers)

[1 2 3]


In [ ]:
# grades = np.array([[87, 96, 70], [100, 87, 90],[94, 77, 90], [100, 81, 82]])
# print(grades)
# grades.sum()
# grades.min()
# grades.max()
# grades.mean()
# grades.std()
# grades.var()
# grades.mean(axis=1)

In [ ]:
import numpy as np
numbers = np.array([1, 4, 9, 16, 25, 36])
np.sqrt(numbers)

array([1., 2., 3., 4., 5., 6.])

In [ ]:
numbers2 = np.arange(1, 7) * 10
numbers2
np.multiply(numbers2, 5)
numbers3 = numbers2.reshape(2, 3)
numbers3
numbers4 = np.array([2, 4, 6])
np.multiply(numbers3, numbers4)

array([[ 20,  80, 180],
       [ 80, 200, 360]])

## Indexing

In [ ]:
# grades = np.array([[87, 96, 70], [100, 87, 90], [94, 77, 90], [100, 81, 82]])
grades = np.array([1,2,3])
print(grades.shape)
# grades[0, 1]
# grades[1]
# grades[0:2]
# grades[[1, 3]]
# a = grades[:, 0]
# b = grades[:, 1:3]
# b.shape

(3,)


In [ ]:
grades = np.array([[87, 96, 70], [100, 87, 90]])
# grades.resize(1, 6)
grades.reshape(1, 6)
flattened = grades.flatten()
grades2 = np.array([[94, 77, 90], [100, 81, 82]])
# np.hstack((grades, grades2))
grades3 = np.hstack((grades, grades2))
print(grades3)

[[ 87  96  70  94  77  90]
 [100  87  90 100  81  82]]


In [ ]:
import pandas as pd
grades = pd.Series([87, 100, 94])
print(grades)
pd.Series(98.6, range(3))
grades[0]
grades.count()
grades.mean()
# grades.min()
# grades.std()
# grades.describe()
# grades = pd.Series([87, 100, 94], index=['Wally', 'Eva', 'Sam'])
grades = pd.Series({'Wally': 87, 'Eva': 100, 'Sam': 94})
grades.dtype
grades


0     87
1    100
2     94
dtype: int64


Wally     87
Eva      100
Sam       94
dtype: int64

In [ ]:
hardware = pd.Series(['Hammer', 'Saw', 'Wrench'])
hardware
hardware.str.contains('a')

0     True
1     True
2    False
dtype: bool

In [ ]:
import numpy as np
nums1 = np.array([[1,2],[2,2],[3,3]])
nums2 = np.array([[1,2,3],[1,2,3]])
print(nums1.shape)
print(nums2.shape)
nums = np.dot(nums2,nums1)
print(nums.shape)
print(nums)

(3, 2)
(2, 3)
(2, 2)
[[14 15]
 [14 15]]
